### ISSUE TITLE
Suggestion about updating scripts that don't contain updateURL or downloadURL

### ISSUE THREAD

**Issue by darkred** [scriptish/scriptish#114]
Currently Scriptish provides an option,
for scripts without updateURL, to use downloadURL for updates, instead.

I'd like to make this suggestion -if possible- :
for scripts that don't contain neither updateURL nor downloadURL,
Scriptish to offer one more option, which, if enabled,
Scriptish (during the script installation) to inject to the script as updateURL
the URL from the awesomebar through which the script is installed.

Thank you

**Comment by nmaier** [comment]
This is theoretically there (see the Main/Update/Use download URL for updates if there is no download URL), but currently intensionally broken for newly installed scripts due to 59a475e2c1c12b483d773680b1fb8e3ab1de084b and issue #94.

It should be noted, however, that this mechanism is also influenced by the secure update preference, which defaults to only allowing updates via https.

As such, I'm closing this ticket as the general option is already there, although currently depending on #94 getting fixed.

**Comment by darkred** [comment]
Thanks for your reply.
